# --------------------------------------------------------
# These properties are the local development properties.
#
# Spring boot uses this file when the application is launched
# with the root of the project set as the working directory.
# These properties take precedence over the classpath
# application.yml.
#
# Using gradle from the commandline means the working
# directory is by default the project root.
#
# Using Intellij you need to setup your run config so the
# working directory is the project root.
# --------------------------------------------------------
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/iat"
    username: "iat"
    password: "${DB_PASSWORD}"

---
spring:
  profiles: dev
  datasource:
    url: "jdbc:postgresql://imrt-qa-db.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

flyway:
  enabled: false

---
spring:
  profiles: uat
  datasource:
    url: "jdbc:postgresql://imrt-db-uat-aurora.cjqp2fdamfoh.us-east-2.rds.amazonaws.com:5432/iat"

flyway:
  enabled: false
