spring:
  datasource:
    url: "jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.schema:iat}"
    username: "${db.user:iat_admin}"
    password: "${db.password}"

flyway:
  enabled: true
  table: "schema_version"