insert into
    tims_user (id, email, given_name, surname, organization_name, organization_type_id, tag, is_deleted, created_by, updated_by)
values (
           1,
           'tims-admin@smarterbalanced.com',
           'TIMS',
           'Admin',
           'Smarter Balanced',
           4,
           'TIMS Admin',
           true,
           1,
           1
       ) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS tims_permission_category  (
    id                      INTEGER     NOT NULL PRIMARY KEY ,
    code                    TEXT        NOT NULL CHECK (char_length(code)  <= 255) UNIQUE,
    label                   TEXT        NOT NULL CHECK (char_length(label)  <= 255) UNIQUE,
    category_order          INTEGER     NOT NULL
);

insert into tims_permission_category (id, code, label, category_order) values (1, 'Application Access', 'Application Access', 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (2, 'Application Admin', 'Application Admin', 2) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (3, 'Item Creation', 'Item Creation', 3) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (4, 'Item Editing', 'Item Editing', 4) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (5, 'Item Workflow', 'Item Workflow', 5) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (6, 'Item Viewing', 'Item Viewing', 6) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (7, 'Item Previewing', 'Item Previewing', 7) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (8, 'Item Search', 'Item Search', 8) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (9, 'Item Assignment', 'Item Assignment', 9) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (10, 'Item Bulk Operations', 'Item Bulk Operations', 10) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (11, 'Item Export', 'Item Export', 11) ON CONFLICT (id) DO NOTHING;
insert into tims_permission_category (id, code, label, category_order) values (12, 'Item Import', 'Item Import', 12) ON CONFLICT (id) DO NOTHING;

CREATE SEQUENCE IF NOT EXISTS tims_permission_seq START 1000;

CREATE TABLE IF NOT EXISTS tims_permission  (
    id                      INTEGER     NOT NULL PRIMARY KEY ,
    code                    TEXT        NOT NULL CHECK (char_length(code)  <= 255) UNIQUE,
    label                   TEXT        NOT NULL CHECK (char_length(label)  <= 255) UNIQUE,
    description             TEXT        NOT NULL CHECK (char_length(description)  <= 510),
    permission_order        INTEGER     NOT NULL,
    permission_category_id  INTEGER     NOT NULL,
    is_workflow_restricted  BOOLEAN     NOT NULL DEFAULT FALSE,
    version                 INTEGER     NOT NULL DEFAULT 1,
    created_by              INTEGER     NOT NULL,
    created_date            TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    updated_by              INTEGER     NOT NULL,
    updated_date            TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    constraint permission_fk_1 foreign key (permission_category_id) references tims_permission_category(id),
    constraint permission_fk_2 foreign key (created_by) references tims_user(id),
    constraint permission_fk_3 foreign key (updated_by) references tims_user(id)
);

insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (1, 'access_tims', 'Log in to TIMS', 'You can log into TIMS.', 1, 1, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (2, 'early_access_qti', 'Access QTI features', 'You can access QTI features before they are finished being developed.', 2, 1, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (3, 'access_admin', 'Access admin', 'You can navigate to the Administration section of TIMS.', 3, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (4, 'create_role', 'Create role', 'You can create TIMS roles', 4, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (5, 'edit_role', 'Edit role', 'You can edit TIMS roles', 5, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (6, 'delete_role', 'Delete role', 'You can delete TIMS roles', 6, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (7, 'create_user', 'Create user', 'You can create TIMS users', 7, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (8, 'edit_user', 'Edit user', 'You can edit TIMS users', 8, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (9, 'delete_user', 'Delete user', 'You can delete TIMS users', 9, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (10, 'edit_permission', 'Edit permission', 'You can edit TIMS permissions', 10, 2, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (11, 'create_eq_item', 'Create EQ item', 'You can create EQ items.', 11, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (12, 'create_ebsr_item', 'Create EBSR item', 'You can create EBSR items.', 12, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (13, 'create_gi_item', 'Create GI item', 'You can create GI items.', 13, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (14, 'create_htqo_item', 'Create HTQO item', 'You can create HTQO items.', 14, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (15, 'create_htqs_item', 'Create HTQS item', 'You can create HTQS items.', 15, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (16, 'create_mc_item', 'Create MC item', 'You can create MC items.', 16, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (17, 'create_mi_item', 'Create MI item', 'You can create MI items.', 17, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (18, 'create_ms_item', 'Create MS item', 'You can create MS items.', 18, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (19, 'create_sa_item', 'Create SA item', 'You can create SA items.', 19, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (20, 'create_ti_item', 'Create TI item', 'You can create TI items.', 20, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (21, 'create_wer_item', 'Create WER item', 'You can create WER items.', 21, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (22, 'create_stim_item', 'Create STIM item', 'You can create STIM items.', 22, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (23, 'create_tut_item', 'Create TUT item', 'You can create TUT items.', 23, 3, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (24, 'edit_item_asl_is_required', 'Edit item ASL "is required"', 'You can edit the "is required" field in the ASL tab in the item authoring interface.', 24, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (25, 'edit_item_asl_is_provided', 'Edit item ASL "is provided"', 'You can edit the "is provided" field in the ASL tab in the item authoring interface.', 25, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (26, 'edit_item_asl_content', 'Edit item ASL content', 'You can edit the content in the ASL tab in the item authoring interface.', 26, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (27, 'edit_item_attachments', 'Edit item attachments', 'You can edit the Attachments tab in the item authoring interface.', 27, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (28, 'edit_item_audio', 'Edit item audio', 'You can edit the Audio tab in the item authoring interface.', 28, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (29, 'edit_item_braille_is_required', 'Edit item braille "is required"', 'You can edit the "is required" field in the Braille tab in the item authoring interface.', 29, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (30, 'edit_item_braille_is_provided', 'Edit item braille "is provided"', 'You can edit the "is provided" field in the Braille tab in the item authoring interface.', 30, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (31, 'edit_item_braille_content', 'Edit item braille content', 'You can edit the content in the Braille tab in the item authoring interface.', 31, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (32, 'edit_item_cc_is_required', 'Edit item CC "is required"', 'You can edit the "is required" field in the CC tab in the item authoring interface.', 32, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (33, 'edit_item_cc_is_provided', 'Edit item CC "is provided"', 'You can edit the "is provided" field in the CC tab in the item authoring interface.', 33, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (34, 'edit_item_cc_content', 'Edit item CC content', 'You can edit the content in the CC tab in the item authoring interface.', 34, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (35, 'edit_item_cc_audio_file_association', 'Edit item CC audio file association', 'You can edit the audio file associations in the CC tab in the item authoring interface.', 35, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (36, 'edit_item_core', 'Edit item core', 'You can edit the left side of the item authoring interface', 36, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (37, 'edit_item_enemies', 'Edit item enemies', 'You can edit the Enemies tab in the item authoring interface.', 37, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (38, 'edit_item_glossary_is_english_provided', 'Edit item glossary "is English provided"', 'You can edit the "is English provided" field in the Glossary tab in the item authoring interface.', 38, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (39, 'edit_item_glossary_is_illustrated_required', 'Edit item glossary "is illustrated required"', 'You can edit the "is illustrated required" field in the Glossary tab in the item authoring interface.', 39, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (40, 'edit_item_glossary_is_illustrated_provided', 'Edit item glossary "is illustrated provided"', 'You can edit the "is illustrated provided" field in the Glossary tab in the item authoring interface.', 40, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (41, 'edit_item_glossary_is_translated_required', 'Edit item glossary "is translated required"', 'You can edit the "is translated required" field in the Glossary tab in the item authoring interface.', 41, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (42, 'edit_item_glossary_is_translated_provided', 'Edit item glossary "is translated provided"', 'You can edit the "is translated provided" field in the Glossary tab in the item authoring interface.', 42, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (43, 'edit_item_glossary_terms', 'Edit item glossary terms', 'You can edit the terms in the Glossary tab in the item authoring interface.', 43, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (44, 'edit_item_images', 'Edit item images', 'You can edit the Images tab in the item authoring interface.', 44, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (45, 'edit_item_metadata', 'Edit item metadata', 'You can edit the Metadata tab in the item authoring interface.', 45, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (46, 'edit_item_review_data_facilitator_feedback', 'Edit item review data facilitator feedback', 'You can edit the Facilitator Feedback section of the Data Review section of the Review tab in the item authoring interface.', 46, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (47, 'edit_item_review_data_your_member_feedback', 'Edit item review data your member feedback', 'You can edit your own feedback in the Member Feedback section of the Data Review section of the Review tab in the item authoring interface.', 47, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (48, 'edit_item_review_data_other_member_feedback', 'Edit item review data other member feedback', 'You can edit other users'' feedback in the Member Feedback section of the Data Review section of the Review tab in the item authoring interface.', 48, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (49, 'edit_item_review_educator_facilitator_feedback', 'Edit item review educator facilitator feedback', 'You can edit the Facilitator Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 49, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (50, 'edit_item_review_educator_your_member_feedback', 'Edit item review educator your member feedback', 'You can edit your own feedback in the Member Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 50, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (51, 'edit_item_review_educator_other_member_feedback', 'Edit item review educator other member feedback', 'You can review other users'' feedback in the Member Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 51, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (52, 'edit_item_scoring_machine', 'Edit the machine scoring rules on the Scoring tab', 'You can edit the machine scoring rules on the Scoring tab in the item authoring interface.', 52, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (53, 'edit_item_scoring_rubric', 'Edit the human readable rubric on the Scoring tab', 'You can edit the human readable rubric on the Scoring tab in the item authoring interface.', 53, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (54, 'edit_item_stimulus', 'Edit item stimulus', 'You can edit the Stimulus tab in the item authoring interface.', 54, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (55, 'edit_item_test_admin', 'Edit item test admin', 'You can edit the Test Admin tab in the item authoring interface.', 55, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (56, 'edit_item_tts_is_vi_required', 'Edit item TTS "is VI required"', 'You can edit the "is TTS for the visually impaired required" field in the Text to Speech tab in the item authoring interface.', 56, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (57, 'edit_item_tts_is_vi_provided', 'Edit item TTS "is VI provided"', 'You can edit the "is TTS for the visually impaired provided" field in the Text to Speech tab in the item authoring interface.', 57, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (58, 'edit_item_tts_is_provided', 'Edit item TTS "is provided"', 'You can edit the "is TTS provided" field in the Text to Speech tab in the item authoring interface.', 58, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (59, 'edit_item_translation_is_required', 'Edit item translation "is required"', 'You can edit the "is required" field in the Translation tab in the item authoring interface.', 59, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (60, 'edit_item_translation_is_provided', 'Edit item translation "is provided"', 'You can edit the "is provided" field in the Translation tab in the item authoring interface.', 60, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (61, 'edit_item_translation_content', 'Edit item translation content', 'You can edit the content in the Translation tab in the item authoring interface.', 61, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (62, 'edit_item_tutorial', 'Edit item tutorial', 'You can edit the Tutorial tab in the item authoring interface.', 62, 4, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (63, 'edit_item_workflow', 'Edit item workflow', 'You can update an item''s workflow status in the Workflow tab in the item authoring interface. You may set the new status according to the normal transition rules.', 63, 5, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (64, 'edit_item_workflow_with_override', 'Edit item workflow with override', 'You can update an item''s workflow status in the Workflow tab in the item authoring interface. You may set the new status to any value.', 64, 5, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (65, 'view_eq_item', 'View EQ item', 'You can view the item authoring page for EQ items.', 65, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (66, 'view_ebsr_item', 'View EBSR item', 'You can view the item authoring page for EBSR items.', 66, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (67, 'view_gi_item', 'View GI item', 'You can view the item authoring page for GI items.', 67, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (68, 'view_htqo_item', 'View HTQO item', 'You can view the item authoring page for HTQO items.', 68, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (69, 'view_htqs_item', 'View HTQS item', 'You can view the item authoring page for HTQS items.', 69, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (70, 'view_mc_item', 'View MC item', 'You can view the item authoring page for MC items.', 70, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (71, 'view_mi_item', 'View MI item', 'You can view the item authoring page for MI items.', 71, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (72, 'view_ms_item', 'View MS item', 'You can view the item authoring page for MS items.', 72, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (73, 'view_sa_item', 'View SA item', 'You can view the item authoring page for SA items.', 73, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (74, 'view_ti_item', 'View TI item', 'You can view the item authoring page for TI items.', 74, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (75, 'view_wer_item', 'View WER item', 'You can view the item authoring page for WER items.', 75, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (76, 'view_stim_item', 'View STIM item', 'You can view the item authoring page for STIM items.', 76, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (77, 'view_tut_item', 'View TUT item', 'You can view the item authoring page for TUT items.', 77, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (78, 'view_eq_item_assigned_to_you', 'View EQ item assigned to you', 'You can view the item authoring page for EQ items assigned to you.', 78, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (79, 'view_ebsr_item_assigned_to_you', 'View EBSR item assigned to you', 'You can view the item authoring page for EBSR items assigned to you.', 79, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (80, 'view_gi_item_assigned_to_you', 'View GI item assigned to you', 'You can view the item authoring page for GI items assigned to you.', 80, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (81, 'view_htqo_item_assigned_to_you', 'View HTQO item assigned to you', 'You can view the item authoring page for HTQO items assigned to you.', 81, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (82, 'view_htqs_item_assigned_to_you', 'View HTQS item assigned to you', 'You can view the item authoring page for HTQS items assigned to you.', 82, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (83, 'view_mc_item_assigned_to_you', 'View MC item assigned to you', 'You can view the item authoring page for MC items assigned to you.', 83, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (84, 'view_mi_item_assigned_to_you', 'View MI item assigned to you', 'You can view the item authoring page for MI items assigned to you.', 84, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (85, 'view_ms_item_assigned_to_you', 'View MS item assigned to you', 'You can view the item authoring page for MS items assigned to you.', 85, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (86, 'view_sa_item_assigned_to_you', 'View SA item assigned to you', 'You can view the item authoring page for SA items assigned to you.', 86, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (87, 'view_ti_item_assigned_to_you', 'View TI item assigned to you', 'You can view the item authoring page for TI items assigned to you.', 87, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (88, 'view_wer_item_assigned_to_you', 'View WER item assigned to you', 'You can view the item authoring page for WER items assigned to you.', 88, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (89, 'view_stim_item_assigned_to_you', 'View STIM item assigned to you', 'You can view the item authoring page for STIM items assigned to you.', 89, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (90, 'view_tut_item_assigned_to_you', 'View TUT item assigned to you', 'You can view the item authoring page for TUT items assigned to you.', 90, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (91, 'view_item_asl', 'View item ASL', 'You can view the ASL tab in the item authoring interface.', 91, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (92, 'view_item_attachments', 'View item attachments', 'You can view the Attachments tab in the item authoring interface.', 92, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (93, 'view_item_audio', 'View item audio', 'You can view the Audio tab in the item authoring interface.', 93, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (94, 'view_item_braille', 'View item braille', 'You can view the Braille tab in the item authoring interface.', 94, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (95, 'view_item_cc', 'View item CC', 'You can view the CC tab in the item authoring interface.', 95, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (96, 'view_item_enemies', 'View item enemies', 'You can view the Enemies tab in the item authoring interface.', 96, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (97, 'view_item_glossary', 'View item glossary', 'You can view the Glossary tab in the item authoring interface.', 97, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (98, 'view_item_history', 'View item history', 'You can view the History tab in the item authoring interface.', 98, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (99, 'view_item_images', 'View item images', 'You can view the Images tab in the item authoring interface.', 99, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (100, 'view_item_metadata', 'View item metadata', 'You can view the Metadata tab in the item authoring interface.', 100, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (101, 'view_item_review', 'View item review', 'You can view the Review tab in the item authoring interface.', 101, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (102, 'view_item_review_data_section', 'View item review data', 'You can view the Data Review section of the Review tab in the item authoring interface.', 102, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (103, 'view_item_review_data_facilitator_feedback', 'View item review data facilitator feedback', 'You can view the Facilitator Feedback section of the Data Review section of the Review tab in the item authoring interface.', 103, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (104, 'view_item_review_data_your_member_feedback', 'View item review data your member feedback', 'You can view your own feedback in the Member Feedback section of the Data Review section of the Review tab in the item authoring interface.', 104, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (105, 'view_item_review_data_other_member_feedback', 'View item review data other member feedback', 'You can view other users'' feedback in the Member Feedback section of the Data Review section of the Review tab in the item authoring interface.', 105, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (106, 'view_item_review_educator_section', 'View item review educator', 'You can view the Educator Committee Review section of the Review tab in the item authoring interface.', 106, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (107, 'view_item_review_educator_facilitator_feedback', 'View item review educator facilitator feedback', 'You can view the Facilitator Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 107, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (108, 'view_item_review_educator_your_member_feedback', 'View item review educator your member feedback', 'You can view your own feedback in the Member Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 108, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (109, 'view_item_review_educator_other_member_feedback', 'View item review educator other member feedback', 'You can review other users'' feedback in the Member Feedback section of the Educator Committee Review section of the Review tab in the item authoring interface.', 109, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (110, 'view_item_scoring', 'View item scoring', 'You can view the Scoring tab in the item authoring interface.', 110, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (111, 'view_item_stimulus', 'View item stimulus', 'You can view the Stimulus tab in the item authoring interface.', 111, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (112, 'view_item_test_admin', 'View item test admin', 'You can view the Test Admin tab in the item authoring interface.', 112, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (113, 'view_item_tts', 'View item text to speech', 'You can view the Text to Speech tab in the item authoring interface.', 113, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (114, 'view_item_translation', 'View item translation', 'You can view the Translation tab in the item authoring interface.', 114, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (115, 'view_item_tutorial', 'View item tutorial', 'You can view the Tutorial tab in the item authoring interface.', 115, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (116, 'view_item_validation', 'View item validation', 'You can view the Validation tab in the item authoring interface.', 116, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (117, 'view_item_workflow', 'View item workflow', 'You can view the Workflow tab in the item authoring interface.', 117, 6, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (118, 'preview_item_current_version', 'Preview item current version', 'You can perview the current version of items.', 118, 7, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (119, 'preview_item_all_versions', 'Preview item all versions', 'You can preview the current and historical version of items.', 119, 7, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (120, 'edit_item_search', 'Edit item search', 'You can configure which filters are used when searching for items, the values of those filters, and the columns that are shown in the returned search results.', 120, 8, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (121, 'edit_item_search_text_filter', 'Edit item search text filter', 'You can turn on and use the "Text" filter when searching for items.', 121, 8, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (122, 'assign_item', 'Assign item', 'You can assign items to all users.', 122, 9, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (123, 'unassign_item', 'Unassign item', 'You can unassign items from all users.', 123, 9, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (124, 'unassign_item_assigned_by_you', 'Unassign item assigned by you', 'You can unassign items from users if you were the one who assigned the items to those users.', 124, 9, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (125, 'bulk_update_asl', 'Access bulk update ASL', 'You can access the ASL section in the Bulk Update section of TIMS.', 125, 10, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (126, 'bulk_update_braille', 'Access bulk update braille', 'You can access the Braille section in the Bulk Update section of TIMS.', 126, 10, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (127, 'bulk_update_glossary', 'Access bulk update glossary', 'You can access the Glossary section in the Bulk Update section of TIMS.', 127, 10, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (128, 'bulk_update_test_admin', 'Access bulk update test admin', 'You can access the Test Admin section in the Bulk Update section of TIMS.', 128, 10, false, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (129, 'export_item', 'Export item', 'You can export an item from the item authoring interface.', 129, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (130, 'export_item_asl', 'Download item ASL attachments', 'You can download an item''s ASL attachments from the ASL tab in the item authoring interface.', 130, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (131, 'export_item_attachments', 'Download item attachments', 'You can download an item''s attachments from the Attachments tab', 131, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (132, 'export_item_audio', 'Download item audio attachments', 'You can download an item''s audio attachments from the Audio tab in the item authoring interface.', 132, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (133, 'export_item_braille', 'Download item braille attachments', 'You can download an item''s braille attachments from the Braille tab in the item authoring interface.', 133, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (134, 'export_item_cc', 'Download item CC attachments', 'You can download an item''s CC attachments from the CC tab in the item authoring interface.', 134, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (135, 'export_item_glossary', 'Download item glossary attachments', 'You can download an item''s glossary attachments from the Glossary tab in the item authoring interface.', 135, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (136, 'export_item_history', 'Download item history', 'You can download an item''s history from the History tab in the item authoring interface.', 136, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (137, 'export_item_images', 'Download item images attachments', 'You can download an item''s images attachments from the Images tab in the item authoring interface.', 137, 11, true, 1, 1) ON CONFLICT (id) DO NOTHING;
insert into tims_permission(id, code, label, description, permission_order, permission_category_id, is_workflow_restricted, created_by, updated_by)  values (138, 'discard_item_imported_data', 'Discard imported item data', 'For items that were imported into TIMS, you can discard the parts of the item that remains unchanged from the original in order to use TIMS to manage those parts of the item. This includes imported items'' EQ editor, GI & TI interactive space, and machine rubrics.', 138, 12, true, 1, 1) ON CONFLICT (id) DO NOTHING;


CREATE TABLE IF NOT EXISTS tims_role_permission  (
    role_id                 INTEGER     NOT NULL,
    permission_id           INTEGER     NOT NULL,
    created_by              INTEGER     NOT NULL,
    created_date            TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
    constraint role_permission_fk_1 foreign key (role_id) references tims_role(id),
    constraint role_permission_fk_2 foreign key (permission_id) references tims_permission(id),
    constraint role_permission_fk_3 foreign key (created_by) references tims_user(id)
);


CREATE TABLE IF NOT EXISTS tims_role_permission_workflow_status  (
    role_id                 INTEGER     NOT NULL,
    permission_id           INTEGER     NOT NULL,
    workflow_status_code    VARCHAR     NOT NULL,
    created_by              INTEGER     NOT NULL,
    created_date            TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    CONSTRAINT pk_role_permission_workflow PRIMARY KEY (role_id, permission_id, workflow_status_code),
    constraint role_permission_workflow_fk_1 foreign key (role_id, permission_id) references tims_role_permission(role_id, permission_id),
    constraint role_permission_workflow_fk_2 foreign key (workflow_status_code) references workflow_status(code),
    constraint role_permission_workflow_fk_3 foreign key (created_by) references tims_user(id)
);

-- Adding a table requires these statements to be run
-- Assumes that iat user has already been created in the database
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES in schema public to "iat";
GRANT SELECT, UPDATE ON ALL SEQUENCES in schema public to "iat";
